secrets={
	"DG_WIFI_SSID":"Guest_PassswortFEHLT",
	"DG_WIFI_PASSWORD":"PASSWORT_HIER",
	"HG_WIFI_SSID":"Gast_PassswortFEHLT",
	"HG_WIFI_PASSWORD":"PASSWORT_HIER",
	"H_WIFI_SSID":"M_PassswortFEHLT",
	"H_WIFI_PASSWORD":"PASSWORT_HIER"
}